// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.slack.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetConversationPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetConversationPlainArgs Empty = new GetConversationPlainArgs();

    /**
     * The ID of the channel
     * 
     */
    @Import(name="channelId", required=true)
    private String channelId;

    /**
     * @return The ID of the channel
     * 
     */
    public String channelId() {
        return this.channelId;
    }

    private GetConversationPlainArgs() {}

    private GetConversationPlainArgs(GetConversationPlainArgs $) {
        this.channelId = $.channelId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetConversationPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetConversationPlainArgs $;

        public Builder() {
            $ = new GetConversationPlainArgs();
        }

        public Builder(GetConversationPlainArgs defaults) {
            $ = new GetConversationPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param channelId The ID of the channel
         * 
         * @return builder
         * 
         */
        public Builder channelId(String channelId) {
            $.channelId = channelId;
            return this;
        }

        public GetConversationPlainArgs build() {
            $.channelId = Objects.requireNonNull($.channelId, "expected parameter 'channelId' to be non-null");
            return $;
        }
    }

}
