// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.slack.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetConversationArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetConversationArgs Empty = new GetConversationArgs();

    /**
     * The ID of the channel
     * 
     */
    @Import(name="channelId", required=true)
    private Output<String> channelId;

    /**
     * @return The ID of the channel
     * 
     */
    public Output<String> channelId() {
        return this.channelId;
    }

    private GetConversationArgs() {}

    private GetConversationArgs(GetConversationArgs $) {
        this.channelId = $.channelId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetConversationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetConversationArgs $;

        public Builder() {
            $ = new GetConversationArgs();
        }

        public Builder(GetConversationArgs defaults) {
            $ = new GetConversationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param channelId The ID of the channel
         * 
         * @return builder
         * 
         */
        public Builder channelId(Output<String> channelId) {
            $.channelId = channelId;
            return this;
        }

        /**
         * @param channelId The ID of the channel
         * 
         * @return builder
         * 
         */
        public Builder channelId(String channelId) {
            return channelId(Output.of(channelId));
        }

        public GetConversationArgs build() {
            $.channelId = Objects.requireNonNull($.channelId, "expected parameter 'channelId' to be non-null");
            return $;
        }
    }

}
