// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.slack.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetUsergroupPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetUsergroupPlainArgs Empty = new GetUsergroupPlainArgs();

    /**
     * The name of the usergroup
     * 
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return The name of the usergroup
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The id of the usergroup
     * 
     * The data source expects exactly one of these fields, you can&#39;t set both.
     * 
     */
    @Import(name="usergroupId")
    private @Nullable String usergroupId;

    /**
     * @return The id of the usergroup
     * 
     * The data source expects exactly one of these fields, you can&#39;t set both.
     * 
     */
    public Optional<String> usergroupId() {
        return Optional.ofNullable(this.usergroupId);
    }

    private GetUsergroupPlainArgs() {}

    private GetUsergroupPlainArgs(GetUsergroupPlainArgs $) {
        this.name = $.name;
        this.usergroupId = $.usergroupId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetUsergroupPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetUsergroupPlainArgs $;

        public Builder() {
            $ = new GetUsergroupPlainArgs();
        }

        public Builder(GetUsergroupPlainArgs defaults) {
            $ = new GetUsergroupPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the usergroup
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        /**
         * @param usergroupId The id of the usergroup
         * 
         * The data source expects exactly one of these fields, you can&#39;t set both.
         * 
         * @return builder
         * 
         */
        public Builder usergroupId(@Nullable String usergroupId) {
            $.usergroupId = usergroupId;
            return this;
        }

        public GetUsergroupPlainArgs build() {
            return $;
        }
    }

}
