provider: slack
major-version: 1
esc:
    enabled: true
env:
    SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
lint: true
providerDefaultBranch: main
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
