// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.slack.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetConversationResult {
    private final String channelId;
    /**
     * @return is a unix timestamp.
     * 
     */
    private final Integer created;
    /**
     * @return is the user ID of the member that created this channel.
     * 
     */
    private final String creator;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private final String id;
    /**
     * @return indicates a conversation is archived. Frozen in time.
     * 
     */
    private final Boolean isArchived;
    /**
     * @return represents this conversation as being part of a Shared Channel
     * with a remote organization.
     * 
     */
    private final Boolean isExtShared;
    /**
     * @return will be true if this channel is the &#34;general&#34; channel that includes
     * all regular team members.
     * 
     */
    private final Boolean isGeneral;
    /**
     * @return explains whether this shared channel is shared between Enterprise
     * Grid workspaces within the same organization.
     * 
     */
    private final Boolean isOrgShared;
    /**
     * @return means the conversation is privileged between two or more members.
     * 
     */
    private final Boolean isPrivate;
    /**
     * @return means the conversation is in some way shared between multiple workspaces.
     * 
     */
    private final Boolean isShared;
    /**
     * @return name of the public or private channel.
     * 
     */
    private final String name;
    /**
     * @return purpose of the channel.
     * 
     */
    private final String purpose;
    /**
     * @return topic for the channel.
     * 
     */
    private final String topic;

    @CustomType.Constructor
    private GetConversationResult(
        @CustomType.Parameter("channelId") String channelId,
        @CustomType.Parameter("created") Integer created,
        @CustomType.Parameter("creator") String creator,
        @CustomType.Parameter("id") String id,
        @CustomType.Parameter("isArchived") Boolean isArchived,
        @CustomType.Parameter("isExtShared") Boolean isExtShared,
        @CustomType.Parameter("isGeneral") Boolean isGeneral,
        @CustomType.Parameter("isOrgShared") Boolean isOrgShared,
        @CustomType.Parameter("isPrivate") Boolean isPrivate,
        @CustomType.Parameter("isShared") Boolean isShared,
        @CustomType.Parameter("name") String name,
        @CustomType.Parameter("purpose") String purpose,
        @CustomType.Parameter("topic") String topic) {
        this.channelId = channelId;
        this.created = created;
        this.creator = creator;
        this.id = id;
        this.isArchived = isArchived;
        this.isExtShared = isExtShared;
        this.isGeneral = isGeneral;
        this.isOrgShared = isOrgShared;
        this.isPrivate = isPrivate;
        this.isShared = isShared;
        this.name = name;
        this.purpose = purpose;
        this.topic = topic;
    }

    public String channelId() {
        return this.channelId;
    }
    /**
     * @return is a unix timestamp.
     * 
     */
    public Integer created() {
        return this.created;
    }
    /**
     * @return is the user ID of the member that created this channel.
     * 
     */
    public String creator() {
        return this.creator;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return indicates a conversation is archived. Frozen in time.
     * 
     */
    public Boolean isArchived() {
        return this.isArchived;
    }
    /**
     * @return represents this conversation as being part of a Shared Channel
     * with a remote organization.
     * 
     */
    public Boolean isExtShared() {
        return this.isExtShared;
    }
    /**
     * @return will be true if this channel is the &#34;general&#34; channel that includes
     * all regular team members.
     * 
     */
    public Boolean isGeneral() {
        return this.isGeneral;
    }
    /**
     * @return explains whether this shared channel is shared between Enterprise
     * Grid workspaces within the same organization.
     * 
     */
    public Boolean isOrgShared() {
        return this.isOrgShared;
    }
    /**
     * @return means the conversation is privileged between two or more members.
     * 
     */
    public Boolean isPrivate() {
        return this.isPrivate;
    }
    /**
     * @return means the conversation is in some way shared between multiple workspaces.
     * 
     */
    public Boolean isShared() {
        return this.isShared;
    }
    /**
     * @return name of the public or private channel.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return purpose of the channel.
     * 
     */
    public String purpose() {
        return this.purpose;
    }
    /**
     * @return topic for the channel.
     * 
     */
    public String topic() {
        return this.topic;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetConversationResult defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private String channelId;
        private Integer created;
        private String creator;
        private String id;
        private Boolean isArchived;
        private Boolean isExtShared;
        private Boolean isGeneral;
        private Boolean isOrgShared;
        private Boolean isPrivate;
        private Boolean isShared;
        private String name;
        private String purpose;
        private String topic;

        public Builder() {
    	      // Empty
        }

        public Builder(GetConversationResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.channelId = defaults.channelId;
    	      this.created = defaults.created;
    	      this.creator = defaults.creator;
    	      this.id = defaults.id;
    	      this.isArchived = defaults.isArchived;
    	      this.isExtShared = defaults.isExtShared;
    	      this.isGeneral = defaults.isGeneral;
    	      this.isOrgShared = defaults.isOrgShared;
    	      this.isPrivate = defaults.isPrivate;
    	      this.isShared = defaults.isShared;
    	      this.name = defaults.name;
    	      this.purpose = defaults.purpose;
    	      this.topic = defaults.topic;
        }

        public Builder channelId(String channelId) {
            this.channelId = Objects.requireNonNull(channelId);
            return this;
        }
        public Builder created(Integer created) {
            this.created = Objects.requireNonNull(created);
            return this;
        }
        public Builder creator(String creator) {
            this.creator = Objects.requireNonNull(creator);
            return this;
        }
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public Builder isArchived(Boolean isArchived) {
            this.isArchived = Objects.requireNonNull(isArchived);
            return this;
        }
        public Builder isExtShared(Boolean isExtShared) {
            this.isExtShared = Objects.requireNonNull(isExtShared);
            return this;
        }
        public Builder isGeneral(Boolean isGeneral) {
            this.isGeneral = Objects.requireNonNull(isGeneral);
            return this;
        }
        public Builder isOrgShared(Boolean isOrgShared) {
            this.isOrgShared = Objects.requireNonNull(isOrgShared);
            return this;
        }
        public Builder isPrivate(Boolean isPrivate) {
            this.isPrivate = Objects.requireNonNull(isPrivate);
            return this;
        }
        public Builder isShared(Boolean isShared) {
            this.isShared = Objects.requireNonNull(isShared);
            return this;
        }
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        public Builder purpose(String purpose) {
            this.purpose = Objects.requireNonNull(purpose);
            return this;
        }
        public Builder topic(String topic) {
            this.topic = Objects.requireNonNull(topic);
            return this;
        }        public GetConversationResult build() {
            return new GetConversationResult(channelId, created, creator, id, isArchived, isExtShared, isGeneral, isOrgShared, isPrivate, isShared, name, purpose, topic);
        }
    }
}
