# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .conversation import *
from .get_conversation import *
from .get_user import *
from .get_usergroup import *
from .provider import *
from .usergroup import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_slack.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_slack.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "slack",
  "mod": "index/conversation",
  "fqn": "pulumi_slack",
  "classes": {
   "slack:index/conversation:Conversation": "Conversation"
  }
 },
 {
  "pkg": "slack",
  "mod": "index/usergroup",
  "fqn": "pulumi_slack",
  "classes": {
   "slack:index/usergroup:Usergroup": "Usergroup"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "slack",
  "token": "pulumi:providers:slack",
  "fqn": "pulumi_slack",
  "class": "Provider"
 }
]
"""
)
