// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a Slack channel
 *
 * ## Required scopes
 *
 * This resource requires the following scopes:
 *
 * If using `bot` tokens:
 *
 * - [channels:read](https://api.slack.com/scopes/channels:read)
 *   (public channels)
 * - [channels:manage](https://api.slack.com/scopes/channels:manage)
 *   (public channels)
 * - [channels:join](https://api.slack.com/scopes/channels:join)
 *   (adopting existing public channels)
 * - [groups:read](https://api.slack.com/scopes/groups:read)
 *   (private channels)
 * - [groups:write](https://api.slack.com/scopes/groups:write)
 *   (private channels)
 *
 * If using `user` tokens:
 *
 * - [channels:read](https://api.slack.com/scopes/channels:read) (public channels)
 * - [channels:write](https://api.slack.com/scopes/channels:manage) (public channels)
 * - [groups:read](https://api.slack.com/scopes/groups:read) (private channels)
 * - [groups:write](https://api.slack.com/scopes/groups:write) (private channels)
 *
 * The Slack API methods used by the resource are:
 *
 * - [conversations.create](https://api.slack.com/methods/conversations.create)
 * - [conversations.join](https://api.slack.com/methods/conversations.join)
 * - [conversations.setTopic](https://api.slack.com/methods/conversations.setTopic)
 * - [conversations.setPurpose](https://api.slack.com/methods/conversations.setPurpose)
 * - [conversations.info](https://api.slack.com/methods/conversations.info)
 * - [conversations.members](https://api.slack.com/methods/conversations.members)
 * - [conversations.kick](https://api.slack.com/methods/conversations.kick)
 * - [conversations.invite](https://api.slack.com/methods/conversations.invite)
 * - [conversations.rename](https://api.slack.com/methods/conversations.rename)
 * - [conversations.archive](https://api.slack.com/methods/conversations.archive)
 * - [conversations.unarchive](https://api.slack.com/methods/conversations.unarchive)
 *
 * If you get `missingScope` errors while using this resource check the scopes against
 * the documentation for the methods above.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as slack from "@pulumi/slack";
 *
 * const test = new slack.Conversation("test", {
 *     isPrivate: true,
 *     permanentMembers: [],
 *     topic: "The topic for my channel",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as slack from "@pulumi/slack";
 *
 * const nonadmin = new slack.Conversation("nonadmin", {
 *     actionOnDestroy: "none",
 *     isPrivate: true,
 *     permanentMembers: [],
 *     topic: "The channel won't be archived on destroy",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as slack from "@pulumi/slack";
 *
 * const adopted = new slack.Conversation("adopted", {
 *     actionOnUpdatePermanentMembers: "none",
 *     adoptExistingChannel: true,
 *     permanentMembers: [],
 *     topic: "Adopt existing, don't kick members",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 *
 * ## Import
 *
 * `slack_conversation` can be imported using the ID of the conversation/channel, e.g.
 *
 * ```sh
 * $ pulumi import slack:index/conversation:Conversation my_conversation C023X7QTFHQ
 * ```
 */
export class Conversation extends pulumi.CustomResource {
    /**
     * Get an existing Conversation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConversationState, opts?: pulumi.CustomResourceOptions): Conversation {
        return new Conversation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'slack:index/conversation:Conversation';

    /**
     * Returns true if the given object is an instance of Conversation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Conversation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Conversation.__pulumiType;
    }

    /**
     * indicates whether the
     * conversation should be archived or left behind on destroy. Valid values are
     * `archive | none`. Note that when set to `none` the conversation will be left
     * as it is  and as a result any subsequent runs of pulumi up with the same
     * name  will fail.
     */
    public readonly actionOnDestroy!: pulumi.Output<string | undefined>;
    /**
     * indicate
     * whether the members should be kick of the channel when removed from
     * `permanentMembers`. When set to `none` the user are never kicked, this prevent
     * a side effect on public channels where user that joined the channel are kicked.
     */
    public readonly actionOnUpdatePermanentMembers!: pulumi.Output<string | undefined>;
    public readonly adoptExistingChannel!: pulumi.Output<boolean | undefined>;
    /**
     * is a unix timestamp.
     */
    public /*out*/ readonly created!: pulumi.Output<number>;
    /**
     * is the user ID of the member that created this channel.
     */
    public /*out*/ readonly creator!: pulumi.Output<string>;
    /**
     * indicates a conversation is archived. Frozen in time.
     */
    public readonly isArchived!: pulumi.Output<boolean | undefined>;
    /**
     * represents this conversation as being part of a Shared Channel
     * with a remote organization.
     */
    public /*out*/ readonly isExtShared!: pulumi.Output<boolean>;
    /**
     * will be true if this channel is the "general" channel that includes
     * all regular team members.
     */
    public /*out*/ readonly isGeneral!: pulumi.Output<boolean>;
    /**
     * explains whether this shared channel is shared between Enterprise
     * Grid workspaces within the same organization.
     */
    public /*out*/ readonly isOrgShared!: pulumi.Output<boolean>;
    /**
     * create a private channel instead of a public one.
     */
    public readonly isPrivate!: pulumi.Output<boolean>;
    /**
     * means the conversation is in some way shared between multiple workspaces.
     */
    public /*out*/ readonly isShared!: pulumi.Output<boolean>;
    /**
     * name of the public or private channel.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * user IDs to add to the channel.
     */
    public readonly permanentMembers!: pulumi.Output<string[] | undefined>;
    /**
     * purpose of the channel.
     */
    public readonly purpose!: pulumi.Output<string | undefined>;
    /**
     * topic for the channel.
     */
    public readonly topic!: pulumi.Output<string | undefined>;

    /**
     * Create a Conversation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConversationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConversationArgs | ConversationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConversationState | undefined;
            resourceInputs["actionOnDestroy"] = state ? state.actionOnDestroy : undefined;
            resourceInputs["actionOnUpdatePermanentMembers"] = state ? state.actionOnUpdatePermanentMembers : undefined;
            resourceInputs["adoptExistingChannel"] = state ? state.adoptExistingChannel : undefined;
            resourceInputs["created"] = state ? state.created : undefined;
            resourceInputs["creator"] = state ? state.creator : undefined;
            resourceInputs["isArchived"] = state ? state.isArchived : undefined;
            resourceInputs["isExtShared"] = state ? state.isExtShared : undefined;
            resourceInputs["isGeneral"] = state ? state.isGeneral : undefined;
            resourceInputs["isOrgShared"] = state ? state.isOrgShared : undefined;
            resourceInputs["isPrivate"] = state ? state.isPrivate : undefined;
            resourceInputs["isShared"] = state ? state.isShared : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["permanentMembers"] = state ? state.permanentMembers : undefined;
            resourceInputs["purpose"] = state ? state.purpose : undefined;
            resourceInputs["topic"] = state ? state.topic : undefined;
        } else {
            const args = argsOrState as ConversationArgs | undefined;
            if ((!args || args.isPrivate === undefined) && !opts.urn) {
                throw new Error("Missing required property 'isPrivate'");
            }
            resourceInputs["actionOnDestroy"] = args ? args.actionOnDestroy : undefined;
            resourceInputs["actionOnUpdatePermanentMembers"] = args ? args.actionOnUpdatePermanentMembers : undefined;
            resourceInputs["adoptExistingChannel"] = args ? args.adoptExistingChannel : undefined;
            resourceInputs["isArchived"] = args ? args.isArchived : undefined;
            resourceInputs["isPrivate"] = args ? args.isPrivate : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["permanentMembers"] = args ? args.permanentMembers : undefined;
            resourceInputs["purpose"] = args ? args.purpose : undefined;
            resourceInputs["topic"] = args ? args.topic : undefined;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["creator"] = undefined /*out*/;
            resourceInputs["isExtShared"] = undefined /*out*/;
            resourceInputs["isGeneral"] = undefined /*out*/;
            resourceInputs["isOrgShared"] = undefined /*out*/;
            resourceInputs["isShared"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Conversation.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Conversation resources.
 */
export interface ConversationState {
    /**
     * indicates whether the
     * conversation should be archived or left behind on destroy. Valid values are
     * `archive | none`. Note that when set to `none` the conversation will be left
     * as it is  and as a result any subsequent runs of pulumi up with the same
     * name  will fail.
     */
    actionOnDestroy?: pulumi.Input<string>;
    /**
     * indicate
     * whether the members should be kick of the channel when removed from
     * `permanentMembers`. When set to `none` the user are never kicked, this prevent
     * a side effect on public channels where user that joined the channel are kicked.
     */
    actionOnUpdatePermanentMembers?: pulumi.Input<string>;
    adoptExistingChannel?: pulumi.Input<boolean>;
    /**
     * is a unix timestamp.
     */
    created?: pulumi.Input<number>;
    /**
     * is the user ID of the member that created this channel.
     */
    creator?: pulumi.Input<string>;
    /**
     * indicates a conversation is archived. Frozen in time.
     */
    isArchived?: pulumi.Input<boolean>;
    /**
     * represents this conversation as being part of a Shared Channel
     * with a remote organization.
     */
    isExtShared?: pulumi.Input<boolean>;
    /**
     * will be true if this channel is the "general" channel that includes
     * all regular team members.
     */
    isGeneral?: pulumi.Input<boolean>;
    /**
     * explains whether this shared channel is shared between Enterprise
     * Grid workspaces within the same organization.
     */
    isOrgShared?: pulumi.Input<boolean>;
    /**
     * create a private channel instead of a public one.
     */
    isPrivate?: pulumi.Input<boolean>;
    /**
     * means the conversation is in some way shared between multiple workspaces.
     */
    isShared?: pulumi.Input<boolean>;
    /**
     * name of the public or private channel.
     */
    name?: pulumi.Input<string>;
    /**
     * user IDs to add to the channel.
     */
    permanentMembers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * purpose of the channel.
     */
    purpose?: pulumi.Input<string>;
    /**
     * topic for the channel.
     */
    topic?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Conversation resource.
 */
export interface ConversationArgs {
    /**
     * indicates whether the
     * conversation should be archived or left behind on destroy. Valid values are
     * `archive | none`. Note that when set to `none` the conversation will be left
     * as it is  and as a result any subsequent runs of pulumi up with the same
     * name  will fail.
     */
    actionOnDestroy?: pulumi.Input<string>;
    /**
     * indicate
     * whether the members should be kick of the channel when removed from
     * `permanentMembers`. When set to `none` the user are never kicked, this prevent
     * a side effect on public channels where user that joined the channel are kicked.
     */
    actionOnUpdatePermanentMembers?: pulumi.Input<string>;
    adoptExistingChannel?: pulumi.Input<boolean>;
    /**
     * indicates a conversation is archived. Frozen in time.
     */
    isArchived?: pulumi.Input<boolean>;
    /**
     * create a private channel instead of a public one.
     */
    isPrivate: pulumi.Input<boolean>;
    /**
     * name of the public or private channel.
     */
    name?: pulumi.Input<string>;
    /**
     * user IDs to add to the channel.
     */
    permanentMembers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * purpose of the channel.
     */
    purpose?: pulumi.Input<string>;
    /**
     * topic for the channel.
     */
    topic?: pulumi.Input<string>;
}
