// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./conversation";
export * from "./getConversation";
export * from "./getUser";
export * from "./getUsergroup";
export * from "./provider";
export * from "./usergroup";

// Export sub-modules:
import * as config from "./config";

export {
    config,
};

// Import resources to register:
import { Conversation } from "./conversation";
import { Usergroup } from "./usergroup";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "slack:index/conversation:Conversation":
                return new Conversation(name, <any>undefined, { urn })
            case "slack:index/usergroup:Usergroup":
                return new Usergroup(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("slack", "index/conversation", _module)
pulumi.runtime.registerResourceModule("slack", "index/usergroup", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("slack", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:slack") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
